PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;

CREATE TABLE "ALBUMS" (
	[ID] VARCHAR UNIQUE NOT NULL,
	[DI] VARCHAR UNIQUE NOT NULL,
	[DS] VARCHAR NOT NULL,
	[DT0] VARCHAR NULL,
	[DT1] VARCHAR NULL,
	[DY] SMALLINT NULL,
	[DG] VARCHAR NULL,
	[DN] SMALLINT NULL,
	[DD] INT NULL,
	[DR] SMALLINT NOT NULL
);

CREATE INDEX "ALBUMS_ID" ON "ALBUMS" ([ID]);
CREATE INDEX "ALBUMS_DS" ON "ALBUMS" ([DS]);

CREATE TABLE "TRACKS" (
	[ID] VARCHAR NOT NULL,
	[TN] SMALLINT NOT NULL,
	[TT0] VARCHAR NULL,
	[TT1] VARCHAR NULL,
	[TD] INT NULL,

	FOREIGN KEY ([ID]) REFERENCES "ALBUMS" ([ID])
		DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "TRACKS_ID" ON "TRACKS" ([ID]);
CREATE UNIQUE INDEX "TRACKS_TID" ON "TRACKS" ([ID], [TN]);

END TRANSACTION;
